# Generated by Django 6.0.6 on 2026-06-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='district',
            field=models.CharField(blank=True, default='', help_text="Rwanda district this town belongs to, e.g. 'Gicumbi', 'Musanze'. Used by find_alternative_destinations to suggest nearby towns when no direct route exists for the user's requested destination.", max_length=80),
        ),
    ]
