from datetime import timedelta
from decimal import Decimal

from django.core.management.base import BaseCommand
from django.utils import timezone

from transit.models import Bus, Company, Route, Seat, Town, Trip


TOWNS = {
    # Kigali
    "Nyabugogo":        "Kigali",
    "Kigali":           "Kigali",
    "Gaseke":           "Kigali",
    "Base":             "Kigali",
    "Kabuga":           "Kigali",

    # Northern Province
    "Gicumbi":          "Gicumbi",
    "Byumba":           "Gicumbi",
    "Rukomo":           "Gicumbi",
    "Miyove":           "Gicumbi",
    "Rushaki":          "Gicumbi",
    "Gatuna":           "Gicumbi",
    "Tetero":           "Gicumbi",
    "Rutare":           "Gicumbi",
    "Butaro":           "Burera",
    "Nkumba":           "Burera",
    "Gakenke":          "Gakenke",
    "Kivuye":           "Gakenke",
    "Ruli":             "Gakenke",
    "Musanze":          "Musanze",
    "Kinigi":           "Musanze",
    "Byangabo":         "Musanze",
    "Janja":            "Musanze",
    "Cyanika":          "Burera",
    "Vunga":            "Burera",
    "Burera":           "Burera",
    "Kirambo":          "Burera",

    # Eastern Province
    "Nyagatare":        "Nyagatare",
    "Karama":           "Nyagatare",
    "Ngarama":          "Nyagatare",
    "Kabarore":         "Nyagatare",
    "Karangazi":        "Nyagatare",
    "Tabagwe":          "Nyagatare",
    "Mimuri":           "Nyagatare",
    "Buguma":           "Nyagatare",
    "Rwimiyaga":        "Nyagatare",
    "Cyabayaga":        "Nyagatare",
    "Kagitumba":        "Nyagatare",
    "Matimba":          "Nyagatare",
    "Bugaragara":       "Nyagatare",
    "Ryabega":          "Nyagatare",
    "Kayonza":          "Kayonza",
    "Kiziguro":         "Kayonza",
    "Rwagitima":        "Kayonza",
    "Kiramuruzi":       "Kayonza",
    "Kabarondo":        "Kayonza",
    "Rwamagana":        "Rwamagana",
    "Muyumbu":          "Rwamagana",
    "Gabiro":           "Ngoma",
    "Ngoma":            "Ngoma",
    "Zaza":             "Ngoma",
    "Sake":             "Ngoma",
    "Nyankora":         "Ngoma",
    "Nyamata":          "Bugesera",
    "Ramiro":           "Bugesera",
    "Rilima":           "Bugesera",
    "Kabukuba":         "Bugesera",
    "Gashora":          "Bugesera",
    "Batima":           "Bugesera",
    "Ruhuha":           "Bugesera",
    "Nyagasambu":       "Bugesera",
    "Nemba":            "Bugesera",
    "Ntunga":           "Bugesera",
    "Cyili":            "Bugesera",
    "Karenge":          "Bugesera",
    "Rusumo":           "Kirehe",
    "Nasho":            "Kirehe",
    "Gatore":           "Kirehe",
    "Nyakarambi":       "Kirehe",
    "Gasetsa":          "Kirehe",
    "Mahama":           "Kirehe",
    "Rwinkwavu":        "Kirehe",
    "Buhabwa":          "Kirehe",

    # Southern Province
    "Muhanga":          "Muhanga",
    "Nyabikenke":       "Muhanga",
    "Ruhango":          "Ruhango",
    "Buhanda":          "Ruhango",
    "Birambo":          "Ruhango",
    "Nyanza":           "Nyanza",
    "Busoro":           "Nyanza",
    "Huye":             "Huye",
    "Ndago":            "Huye",
    "Gakoma":           "Huye",
    "Gikonko":          "Huye",
    "Agatunda":         "Huye",
    "Mugombwa":         "Huye",
    "Akanyaru":         "Huye",
    "Gisagara":         "Gisagara",
    "Nyamagabe":        "Nyamagabe",
    "Gasarenda":        "Nyamagabe",
    "Kitabi":           "Nyamagabe",
    "Pindura":          "Nyamagabe",
    "Bweyeye":          "Nyamagabe",
    "Mushubi":          "Nyamagabe",
    "Kaduha":           "Nyamagabe",
    "Manwari":          "Nyamagabe",
    "Nyaruguru":        "Nyaruguru",
    "Kibeho":           "Nyaruguru",
    "Munini":           "Nyaruguru",
    "Nyabimata":        "Nyaruguru",
    "Ruheru":           "Nyaruguru",
    "Kamonyi":          "Kamonyi",
    "Remera Rukoma":    "Kamonyi",
    "Rugarika":         "Kamonyi",
    "Kinazi":           "Kamonyi",
    "Mugina":           "Kamonyi",
    "Kayenzi":          "Kamonyi",

    # Western Province
    "Kamembe":          "Rusizi",
    "Gatumba":          "Rusizi",
    "Bugarama":         "Rusizi",
    "Rusizi":           "Rusizi",
    "Cimerwa":          "Rusizi",
    "Ntango":           "Rusizi",
    "Bushenge":         "Rusizi",
    "Buhabwa":          "Rusizi",
    "Rubavu":           "Rubavu",
    "Gisenyi":          "Rubavu",
    "Bugeshi":          "Rubavu",
    "Kayove":           "Rubavu",
    "Kabuhanga":        "Rubavu",
    "Brasserie":        "Rubavu",
    "Nkora":            "Rubavu",
    "Ngororero":        "Ngororero",
    "Kabaya":           "Ngororero",
    "Mukamira":         "Ngororero",
    "Mahoko":           "Ngororero",
    "Kabali":           "Ngororero",
    "Tyazo":            "Ngororero",
    "Nyarusange":       "Ngororero",
    "Buringa":          "Ngororero",
    "Kibangu":          "Ngororero",
    "Rutsiro":          "Rutsiro",
    "Nyange":           "Rutsiro",
    "Rufungo":          "Rutsiro",
    "Mushubati":        "Rutsiro",
    "Rambura":          "Ngororero",
    "Karongi":          "Karongi",
    "Rubengera":        "Karongi",
    "Gishyita":         "Karongi",
    "Mugonero":         "Karongi",
    "Mubuga":           "Karongi",
    "Karengera":        "Karongi",
    "Gakeri":           "Karongi",
    "Nkomero":          "Karongi",
    "Gisiza":           "Karongi",
    "Congo Nile":       "Karongi",
    "Gisovu":           "Karongi",
    "Pfunda":           "Karongi",
    "Kigeyo":           "Karongi",
    "Hanika":           "Karongi",
    "Nyamasheke":       "Nyamasheke",
    "Ntendezi":         "Nyamasheke",
    "Kirambo":          "Nyamasheke",
}

# All routes extracted from the RURA 2026 official tariff PDF.
# Format: (origin, destination, price_frw)
ROUTES = [
    # === ICYEREKEZO 1: NYABUGOGO – GICUMBI – GATUNA ===
    ("Rukomo",      "Gicumbi",          416),
    ("Gaseke",      "Rukomo",           910),
    ("Miyove",      "Base",             951),
    ("Nyabugogo",   "Gaseke",           1169),
    ("Gicumbi",     "Tetero",           1188),
    ("Gaseke",      "Gicumbi",          1247),
    ("Rukomo",      "Gatuna",           1406),
    ("Gicumbi",     "Gatuna",           1465),
    ("Miyove",      "Gakenke",          1505),
    ("Kivuye",      "Butaro",           1625),
    ("Gicumbi",     "Base",             1980),
    ("Gicumbi",     "Rutare",           1980),
    ("Nyabugogo",   "Rukomo",           2040),
    ("Gaseke",      "Gatuna",           2079),
    ("Nyabugogo",   "Gicumbi",          2297),
    ("Gicumbi",     "Gakenke",          2713),
    ("Gicumbi",     "Kivuye",           2730),
    ("Miyove",      "Musanze",          2772),
    ("Nyabugogo",   "Gatuna",           3248),
    ("Gicumbi",     "Musanze",          4356),
    ("Gicumbi",     "Butaro",           4356),
    ("Musanze",     "Burera",           6336),

    # === ICYEREKEZO 2: NYABUGOGO – MUSANZE – RUBAVU ===
    ("Musanze",     "Kinigi",           436),
    ("Base",        "Gakenke",          515),
    ("Musanze",     "Byangabo",         693),
    ("Musanze",     "Mukamira",         1050),
    ("Musanze",     "Cyanika",          1050),
    ("Musanze",     "Vunga",            1287),
    ("Gakenke",     "Musanze",          1307),
    ("Musanze",     "Kabali",           1782),
    ("Base",        "Musanze",          1801),
    ("Musanze",     "Mahoko",           2099),
    ("Nyabugogo",   "Base",             2158),
    ("Base",        "Kirambo",          2198),
    ("Musanze",     "Kabaya",           2258),
    ("Gakenke",     "Mukamira",         2357),
    ("Nyabugogo",   "Gakenke",          2416),
    ("Musanze",     "Janja",            2534),
    ("Musanze",     "Butaro",           2573),
    ("Musanze",     "Rubavu",           2573),
    ("Nyabugogo",   "Rushaki",          2693),
    ("Musanze",     "Kirambo",          2970),
    ("Musanze",     "Ngororero",        3485),
    ("Base",        "Butaro",           3783),
    ("Nyabugogo",   "Musanze",          3821),
    ("Nyabugogo",   "Butaro",           5940),

    # === ICYEREKEZO 3: GICUMBI – NYAGATARE ===
    ("Rushaki",     "Karama",           990),
    ("Karama",      "Rukomo",           634),
    ("Karama",      "Nyagatare",        1505),
    ("Ngarama",     "Nyagatare",        1525),
    ("Gicumbi",     "Rushaki",          2198),
    ("Rushaki",     "Nyagatare",        2297),
    ("Gicumbi",     "Karama",           2732),
    ("Gicumbi",     "Ngarama",          2970),
    ("Nyabugogo",   "Ngarama",          3960),
    ("Gicumbi",     "Nyagatare",        4535),
    ("Nyabugogo",   "Nyagatare",        5346),

    # === ICYEREKEZO 1: NYABUGOGO – KAYONZA – NYAGATARE ===
    ("Karangazi",   "Ryabega",          198),
    ("Kiramuruzi",  "Kiziguro",         297),
    ("Kiziguro",    "Rwagitima",        337),
    ("Rwagitima",   "Kabarore",         337),
    ("Bugaragara",  "Rwimiyaga",        337),
    ("Kabarore",    "Gabiro",           356),
    ("Matimba",     "Kagitumba",        377),
    ("Ryabega",     "Bugaragara",       416),
    ("Rwimiyaga",   "Matimba",          494),
    ("Kayonza",     "Kiramuruzi",       634),
    ("Kiramuruzi",  "Rwagitima",        634),
    ("Kiziguro",    "Kabarore",         673),
    ("Rwagitima",   "Gabiro",           673),
    ("Gabiro",      "Karangazi",        753),
    ("Ryabega",     "Rwimiyaga",        753),
    ("Ryabega",     "Nyagatare",        832),
    ("Bugaragara",  "Matimba",          832),
    ("Rwimiyaga",   "Kagitumba",        871),
    ("Gabiro",      "Ryabega",          951),
    ("Nyagatare",   "Mimuri",           951),
    ("Nyagatare",   "Bugaragara",       951),
    ("Kiziguro",    "Gabiro",           990),
    ("Kiramuruzi",  "Kabarore",         1050),
    ("Kabarore",    "Karangazi",        1050),
    ("Karangazi",   "Nyagatare",        1050),
    ("Kayonza",     "Kiziguro",         1208),
    ("Bugaragara",  "Kagitumba",        1208),
    ("Kabarore",    "Ryabega",          1247),
    ("Ryabega",     "Matimba",          1247),
    ("Kiramuruzi",  "Gabiro",           1287),
    ("Nyagatare",   "Rwimiyaga",        1287),
    ("Rwagitima",   "Karangazi",        1406),
    ("Gabiro",      "Nyagatare",        1465),
    ("Kayonza",     "Rwagitima",        1544),
    ("Rwamagana",   "Kiramuruzi",       1544),
    ("Rwagitima",   "Ryabega",          1624),
    ("Kabarore",    "Nyagatare",        1663),
    ("Karama",      "Nyagatare",        1702),
    ("Kiziguro",    "Karangazi",        1742),
    ("Rwamagana",   "Kiziguro",         1742),
    ("Nyagatare",   "Matimba",          1742),
    ("Kayonza",     "Kabarore",         1881),
    ("Kiziguro",    "Ryabega",          1960),
    ("Ryabega",     "Kagitumba",        1960),
    ("Kiramuruzi",  "Karangazi",        2040),
    ("Rwagitima",   "Nyagatare",        2139),
    ("Nyagatare",   "Kagitumba",        2158),
    ("Kayonza",     "Gabiro",           2217),
    ("Kiramuruzi",  "Ryabega",          2237),
    ("Rwamagana",   "Rwagitima",        2416),
    ("Kiziguro",    "Nyagatare",        2435),
    ("Rwamagana",   "Kabarore",         2594),
    ("Kiramuruzi",  "Nyagatare",        2752),
    ("Kabarore",    "Kagitumba",        2911),
    ("Kayonza",     "Karangazi",        2950),
    ("Rwamagana",   "Gabiro",           2950),
    ("Kabuga",      "Kiramuruzi",       3009),
    ("Nyabugogo",   "Kayonza",          3129),
    ("Kayonza",     "Ryabega",          3168),
    ("Kayonza",     "Nyagatare",        3584),
    ("Rwamagana",   "Karangazi",        3664),
    ("Rwamagana",   "Ryabega",          3880),
    ("Kabuga",      "Kabarore",         4079),
    ("Nyabugogo",   "Kiramuruzi",       4158),
    ("Rwamagana",   "Nyagatare",        4257),
    ("Rwamagana",   "Bugaragara",       4316),
    ("Nyabugogo",   "Kiziguro",         4356),
    ("Rwamagana",   "Rwimiyaga",        4613),
    ("Nyabugogo",   "Rwagitima",        4792),
    ("Nyabugogo",   "Kabarore",         5010),
    ("Rwamagana",   "Matimba",          5148),
    ("Kabuga",      "Karangazi",        5148),
    ("Kabuga",      "Ryabega",          5366),
    ("Rwamagana",   "Kagitumba",        5525),
    ("Nyabugogo",   "Gabiro",           5584),
    ("Kabuga",      "Nyagatare",        5900),
    ("Nyabugogo",   "Karangazi",        6058),
    ("Kabuga",      "Rwimiyaga",        6118),
    ("Nyabugogo",   "Ryabega",          6276),
    ("Kabuga",      "Matimba",          6653),
    ("Nyabugogo",   "Bugaragara",       6811),
    ("Kabuga",      "Kagitumba",        7029),
    ("Nyabugogo",   "Rwimiyaga",        7147),
    ("Nyabugogo",   "Matimba",          7643),
    ("Nyabugogo",   "Kagitumba",        7900),

    # === ICYEREKEZO 2: NYABUGOGO – RWAMAGANA – RUSUMO ===
    ("Kabuga",      "Muyumbu",          356),
    ("Gatore",      "Nyakarambi",       455),
    ("Kabarondo",   "Rwinkwavu",        515),
    ("Kabuga",      "Nyagasambu",       595),
    ("Rwamagana",   "Kayonza",          634),
    ("Kayonza",     "Kabarondo",        653),
    ("Kabarondo",   "Ngoma",            653),
    ("Kabarondo",   "Nyankora",         792),
    ("Nyagasambu",  "Rwamagana",        910),
    ("Nyakarambi",  "Rusumo",           910),
    ("Kabuga",      "Ntunga",           930),
    ("Ngoma",       "Gatore",           1050),
    ("Ngoma",       "Rwinkwavu",        1149),
    ("Kayonza",     "Rwinkwavu",        1188),
    ("Rwamagana",   "Kabarondo",        1287),
    ("Gatore",      "Rusumo",           1326),
    ("Kabuga",      "Cyili",            1326),
    ("Kabuga",      "Karenge",          1386),
    ("Ngoma",       "Nyankora",         1426),
    ("Kayonza",     "Ngoma",            1465),
    ("Kayonza",     "Nyankora",         1484),
    ("Kabuga",      "Rwamagana",        1484),
    ("Ngoma",       "Nyakarambi",       1525),
    ("Nyabugogo",   "Nyagasambu",       1604),
    ("Nyagasambu",  "Kayonza",          1624),
    ("Kabarondo",   "Gatore",           1684),
    ("Rwamagana",   "Rwinkwavu",        1900),
    ("Rwamagana",   "Ngoma",            2040),
    ("Kabarondo",   "Nyakarambi",       2139),
    ("Rwamagana",   "Nyankora",         2217),
    ("Kabuga",      "Kayonza",          2217),
    ("Ngoma",       "Rusumo",           2316),
    ("Nyabugogo",   "Rwamagana",        2495),
    ("Gasetsa",     "Rusumo",           2633),
    ("Kayonza",     "Nyakarambi",       2832),
    ("Kabuga",      "Kabarondo",        2890),
    ("Kabarondo",   "Rusumo",           2950),
    ("Rwamagana",   "Gatore",           3089),
    ("Kabarondo",   "Nasho",            3267),
    ("Kabuga",      "Ngoma",            3544),
    ("Rwamagana",   "Nyakarambi",       3563),
    ("Kayonza",     "Rusumo",           3821),
    ("Ngoma",       "Nasho",            3921),
    ("Nyabugogo",   "Kabarondo",        3940),
    ("Kayonza",     "Nasho",            3979),
    ("Rwamagana",   "Rusumo",           4237),
    ("Nyabugogo",   "Ngoma",            4574),
    ("Rwamagana",   "Nasho",            4693),
    ("Kabuga",      "Nyakarambi",       5029),
    ("Nyabugogo",   "Buhabwa",          5484),
    ("Nyabugogo",   "Gatore",           5623),
    ("Kabuga",      "Rusumo",           5980),
    ("Nyabugogo",   "Nyakarambi",       6079),
    ("Nyabugogo",   "Rusumo",           7029),
    ("Nyabugogo",   "Mahama",           7921),

    # === ICYEREKEZO 3: NYABUGOGO – BUGESERA – ZAZA ===
    ("Ramiro",      "Batima",           792),
    ("Sake",        "Gashora",          871),
    ("Nyamata",     "Ramiro",           990),
    ("Sake",        "Ramiro",           1109),
    ("Zaza",        "Gashora",          1346),
    ("Nyamata",     "Kabukuba",         1445),
    ("Nyamata",     "Rilima",           1465),
    ("Zaza",        "Ramiro",           1585),
    ("Nyamata",     "Batima",           1702),
    ("Nyamata",     "Ruhuha",           1822),
    ("Sake",        "Nyamata",          2000),
    ("Busoro",      "Nyanza",           2019),
    ("Nyamata",     "Nemba",            2118),
    ("Ngoma",       "Gashora",          2139),
    ("Nyanza",      "Ramiro",           2198),
    ("Nyanza",      "Gashora",          2297),
    ("Nyanza",      "Rilima",           2297),
    ("Ngoma",       "Ramiro",           2357),
    ("Nyamata",     "Ruhuha",           2456),
    ("Zaza",        "Nyamata",          2474),
    ("Nyanza",      "Ruhuha",           2515),
    ("Nyanza",      "Kabukuba",         2752),
    ("Nyamata",     "Nyanza",           2871),
    ("Nyanza",      "Nemba",            3168),
    ("Busoro",      "Huye",             3207),
    ("Ngoma",       "Nyamata",          3267),
    ("Nyanza",      "Ruhuha",           3901),
    ("Nyamata",     "Huye",             3921),
    ("Nyanza",      "Sake",             4138),
    ("Nyanza",      "Zaza",             5049),

    # === ICYEREKEZO 1: NYABUGOGO – MUHANGA – HUYE – NYAMAGABE ===
    ("Huye",        "Gisagara",         653),
    ("Gasarenda",   "Kitabi",           712),
    ("Ruhango",     "Nyanza",           753),
    ("Nyamagabe",   "Gasarenda",        852),
    ("Nyabugogo",   "Kamonyi",          914),
    ("Nyamagabe",   "Manwari",          930),
    ("Ruhango",     "Buhanda",          1069),
    ("Buhanda",     "Nyanza",           1069),
    ("Muhanga",     "Ruhango",          1089),
    ("Huye",        "Nyamagabe",        1109),
    ("Huye",        "Kibeho",           1247),
    ("Nyabugogo",   "Rugarika",         1287),
    ("Pindura",     "Bweyeye",          1287),
    ("Nyamagabe",   "Kitabi",           1367),
    ("Muhanga",     "Remera Rukoma",    1406),
    ("Nyanza",      "Huye",             1465),
    ("Huye",        "Ndago",            1544),
    ("Muhanga",     "Mugina",           1544),
    ("Muhanga",     "Nyanza",           1624),
    ("Nyamagabe",   "Mushubi",          1663),
    ("Huye",        "Gakoma",           1723),
    ("Muhanga",     "Buhanda",          1822),
    ("Muhanga",     "Kinazi",           1842),
    ("Huye",        "Gasarenda",        1921),
    ("Ruhango",     "Birambo",          1980),
    ("Huye",        "Gikonko",          1980),
    ("Huye",        "Munini",           2000),
    ("Kamembe",     "Pindura",          2019),
    ("Nyabugogo",   "Muhanga",          2040),
    ("Ruhango",     "Huye",             2118),
    ("Huye",        "Mugombwa",         2118),
    ("Nyabugogo",   "Kayenzi",          2139),
    ("Nyabugogo",   "Kinazi",           2178),
    ("Muhanga",     "Nyabikenke",       2237),
    ("Nyanza",      "Nyamagabe",        2474),
    ("Huye",        "Kitabi",           2495),
    ("Huye",        "Akanyaru",         2515),
    ("Huye",        "Munini",           2653),
    ("Nyamagabe",   "Pindura",          2772),
    ("Huye",        "Mushubi",          2791),
    ("Huye",        "Agatunda",         2970),
    ("Nyabugogo",   "Ruhango",          2950),
    ("Muhanga",     "Huye",             3089),
    ("Ruhango",     "Kaduha",           3089),
    ("Nyanza",      "Gasarenda",        3148),
    ("Ruhango",     "Nyamagabe",        3228),
    ("Kamembe",     "Bweyeye",          3326),
    ("Kitabi",      "Kamembe",          3446),
    ("Nyabugogo",   "Nyanza",           3664),
    ("Nyanza",      "Kitabi",           3861),
    ("Huye",        "Pindura",          3901),
    ("Ruhango",     "Gasarenda",        3960),
    ("Huye",        "Nyabimata",        3960),
    ("Huye",        "Ruheru",           3960),
    ("Nyamagabe",   "Bweyeye",          4079),
    ("Muhanga",     "Nyamagabe",        4158),
    ("Gasarenda",   "Kamembe",          4158),
    ("Muhanga",     "Gasarenda",        4911),
    ("Nyamagabe",   "Kamembe",          4990),
    ("Nyabugogo",   "Huye",             5068),
    ("Huye",        "Bweyeye",          5187),
    ("Muhanga",     "Kitabi",           5623),
    ("Nyabugogo",   "Kaduha",           5940),
    ("Huye",        "Kamembe",          6198),
    ("Nyabugogo",   "Nyamagabe",        6653),
    ("Nyabugogo",   "Gasarenda",        6871),
    ("Nyanza",      "Kamembe",          7306),
    ("Nyabugogo",   "Kitabi",           7563),
    ("Ruhango",     "Kamembe",          8514),
    ("Nyabugogo",   "Mushubi",          9524),
    ("Muhanga",     "Kamembe",          9603),
    ("Nyabugogo",   "Pindura",          10930),
    ("Nyabugogo",   "Kamembe",          11445),

    # === ICYEREKEZO 1: NYABUGOGO – MUHANGA – KARONGI – KAMEMBE ===
    ("Rufungo",     "Rambura",          218),
    ("Mubuga",      "Gishyita",         257),
    ("Hanika",      "Kirambo",          297),
    ("Tyazo",       "Nyamasheke",       337),
    ("Karengera",   "Hanika",           377),
    ("Nyange",      "Rufungo",          416),
    ("Gishyita",    "Mugonero",         416),
    ("Hanika",      "Tyazo",            416),
    ("Kirambo",     "Nyamasheke",       455),
    ("Muhanga",     "Nyarusange",       614),
    ("Nyange",      "Rambura",          634),
    ("Rambura",     "Rubengera",        673),
    ("Rubengera",   "Karongi",          673),
    ("Mubuga",      "Mugonero",         673),
    ("Karengera",   "Kirambo",          673),
    ("Nyarusange",  "Nyange",           673),
    ("Mugonero",    "Karengera",        712),
    ("Karongi",     "Mubuga",           753),
    ("Hanika",      "Nyamasheke",       753),
    ("Karengera",   "Tyazo",            792),
    ("Kamembe",     "Bushenge",         852),
    ("Rufungo",     "Rubengera",        891),
    ("Karongi",     "Gishyita",         1069),
    ("Nyarusange",  "Rufungo",          1089),
    ("Mugonero",    "Hanika",           1089),
    ("Gishyita",    "Karengera",        1128),
    ("Karengera",   "Nyamasheke",       1128),
    ("Muhanga",     "Nyange",           1188),
    ("Nyange",      "Rubengera",        1307),
    ("Rambura",     "Congo Nile",       1326),
    ("Mubuga",      "Karengera",        1367),
    ("Mugonero",    "Kirambo",          1367),
    ("Karongi",     "Mugonero",         712),
    ("Rufungo",     "Karongi",          1643),
    ("Muhanga",     "Rufungo",          1702),
    ("Rubengera",   "Gishyita",         1702),
    ("Mubuga",      "Hanika",           1742),
    ("Gishyita",    "Kirambo",          1782),
    ("Mugonero",    "Nyamasheke",       1822),
    ("Tyazo",       "Kamembe",          1822),
    ("Nyarusange",  "Rambura",          1307),
    ("Rambura",     "Mubuga",           2118),
    ("Rubengera",   "Mugonero",         2118),
    ("Mubuga",      "Tyazo",            2158),
    ("Kamembe",     "Cimerwa",          2178),
    ("Kamembe",     "Ntango",           2198),
    ("Gishyita",    "Nyamasheke",       2237),
    ("Hanika",      "Kamembe",          2258),
    ("Rufungo",     "Mubuga",           2336),
    ("Rambura",     "Gishyita",         2376),
    ("Mubuga",      "Nyamasheke",       2495),
    ("Nyabugogo",   "Nyarusange",       2573),
    ("Rufungo",     "Gishyita",         2594),
    ("Karongi",     "Hanika",           2594),
    ("Karengera",   "Kamembe",          2614),
    ("Nyarusange",  "Congo Nile",       2633),
    ("Muhanga",     "Rubengera",        2674),
    ("Nyarusange",  "Karongi",          2713),
    ("Nyange",      "Mubuga",           2752),
    ("Karongi",     "Kirambo",          2752),
    ("Rambura",     "Karongi",          1426),
    ("Rubengera",   "Karengera",        2832),
    ("Karongi",     "Tyazo",            2832),
    ("Muhanga",     "Mushubati",        2911),
    ("Karongi",     "Nyamasheke",       2989),
    ("Nyange",      "Gishyita",         3009),
    ("Rufungo",     "Mugonero",         3009),
    ("Rubengera",   "Hanika",           3207),
    ("Muhanga",     "Congo Nile",       3267),
    ("Nyabugogo",   "Nyange",           3366),
    ("Mugonero",    "Kamembe",          3405),
    ("Nyarusange",  "Mubuga",           3425),
    ("Nyange",      "Mugonero",         3425),
    ("Rubengera",   "Kirambo",          3485),
    ("Rambura",     "Karengera",        3505),
    ("Karongi",     "Ntendezi",         3604),
    ("Rubengera",   "Tyazo",            3623),
    ("Nyabugogo",   "Rufungo",          3643),
    ("Nyarusange",  "Gishyita",         3664),
    ("Rufungo",     "Karengera",        3722),
    ("Muhanga",     "Karongi",          3742),
    ("Gishyita",    "Kamembe",          3781),
    ("Rambura",     "Hanika",           3880),
    ("Rubengera",   "Nyamasheke",       3960),
    ("Mubuga",      "Kamembe",          4020),
    ("Muhanga",     "Mubuga",           4039),
    ("Nyarusange",  "Mugonero",         4079),
    ("Rufungo",     "Hanika",           4079),
    ("Nyange",      "Karengera",        4119),
    ("Nyabugogo",   "Rambura",          4138),
    ("Rambura",     "Kirambo",          4158),
    ("Muhanga",     "Gishyita",         4296),
    ("Rambura",     "Tyazo",            4296),
    ("Rufungo",     "Kirambo",          4376),
    ("Nyange",      "Hanika",           4495),
    ("Rufungo",     "Tyazo",            4495),
    ("Nyabugogo",   "Rubengera",        4535),
    ("Rambura",     "Nyamasheke",       4613),
    ("Muhanga",     "Mugonero",         4712),
    ("Nyarusange",  "Karengera",        4792),
    ("Nyange",      "Kirambo",          4792),
    ("Karongi",     "Kamembe",          4792),
    ("Rufungo",     "Nyamasheke",       4831),
    ("Nyabugogo",   "Mushubati",        4870),
    ("Nyange",      "Tyazo",            4911),
    ("Nyarusange",  "Hanika",           5168),
    ("Nyabugogo",   "Congo Nile",       5208),
    ("Nyange",      "Nyamasheke",       5247),
    ("Muhanga",     "Karengera",        5405),
    ("Rubengera",   "Kamembe",          5445),
    ("Nyarusange",  "Kirambo",          5465),
    ("Nyabugogo",   "Karongi",          5504),
    ("Nyarusange",  "Tyazo",            5584),
    ("Muhanga",     "Hanika",           5782),
    ("Nyarusange",  "Nyamasheke",       5920),
    ("Nyabugogo",   "Mubuga",           5980),
    ("Muhanga",     "Kirambo",          6079),
    ("Rambura",     "Kamembe",          6118),
    ("Muhanga",     "Tyazo",            6198),
    ("Nyabugogo",   "Gishyita",         6237),
    ("Rufungo",     "Kamembe",          6336),
    ("Muhanga",     "Nyamasheke",       6534),
    ("Nyabugogo",   "Mugonero",         6653),
    ("Nyange",      "Kamembe",          6752),
    ("Nyabugogo",   "Karengera",        7365),
    ("Nyarusange",  "Kamembe",          7406),
    ("Nyabugogo",   "Hanika",           7742),
    ("Nyabugogo",   "Kirambo",          8019),
    ("Nyabugogo",   "Tyazo",            8158),
    ("Nyabugogo",   "Nyamasheke",       8474),
    ("Muhanga",     "Kamembe",          9603),
    ("Nyabugogo",   "Kamembe",          10296),

    # === ICYEREKEZO 2: NYABUGOGO – MUHANGA – NGORORERO – RUBAVU ===
    ("Gatumba",     "Ngororero",        515),
    ("Buringa",     "Gatumba",          712),
    ("Muhanga",     "Buringa",          753),
    ("Kabaya",      "Mukamira",         1069),
    ("Buringa",     "Ngororero",        1227),
    ("Ngororero",   "Kabaya",           1386),
    ("Muhanga",     "Gatumba",          1465),
    ("Gatumba",     "Kabaya",           1663),
    ("Kabaya",      "Kabali",           1822),
    ("Muhanga",     "Ngororero",        1941),
    ("Ngororero",   "Mukamira",         2040),
    ("Muhanga",     "Kibangu",          2139),
    ("Kabaya",      "Mahoko",           2237),
    ("Buringa",     "Kabaya",           2376),
    ("Kabaya",      "Rubavu",           2495),
    ("Nyabugogo",   "Buringa",          2693),
    ("Ngororero",   "Kabali",           2970),
    ("Muhanga",     "Kabaya",           3129),
    ("Ngororero",   "Mahoko",           3386),
    ("Nyabugogo",   "Gatumba",          3405),
    ("Buringa",     "Mukamira",         3544),
    ("Gatumba",     "Mukamira",         3563),
    ("Ngororero",   "Rubavu",           3604),
    ("Buringa",     "Kabali",           4197),
    ("Gatumba",     "Kabali",           4237),
    ("Muhanga",     "Mukamira",         4257),
    ("Nyabugogo",   "Ngororero",        4395),
    ("Muhanga",     "Kabali",           4950),
    ("Nyabugogo",   "Kabaya",           5068),
    ("Buringa",     "Rubavu",           5208),
    ("Gatumba",     "Rubavu",           5227),
    ("Muhanga",     "Mahoko",           5366),
    ("Muhanga",     "Rubavu",           5683),
    ("Nyabugogo",   "Mukamira",         4831),
    ("Nyabugogo",   "Mahoko",           5860),
    ("Nyabugogo",   "Rubavu",           6554),

    # === ICYEREKEZO 3: NYABUGOGO – NYABIHU – RUBAVU ===
    ("Kabali",      "Mahoko",           337),
    ("Byangabo",    "Mukamira",         377),
    ("Mukamira",    "Kabali",           712),
    ("Kabali",      "Rubavu",           951),
    ("Mukamira",    "Mahoko",           1050),
    ("Byangabo",    "Kabali",           1089),
    ("Byangabo",    "Mahoko",           1406),
    ("Mukamira",    "Rubavu",           1525),
    ("Rubavu",      "Bugeshi",          1861),
    ("Rubavu",      "Kabuhanga",        1980),
    ("Gakenke",     "Byangabo",         2000),
    ("Byangabo",    "Rubavu",           2040),
    ("Base",        "Byangabo",         2495),
    ("Base",        "Mukamira",         2871),
    ("Gakenke",     "Kabali",           3069),
    ("Gakenke",     "Mahoko",           3405),
    ("Base",        "Kabali",           3584),
    ("Base",        "Mahoko",           3921),
    ("Gakenke",     "Rubavu",           4020),
    ("Nyabugogo",   "Byangabo",         4455),
    ("Base",        "Rubavu",           4535),

    # === ICYEREKEZO 4: RUBAVU – KARONGI – KAMEMBE ===
    ("Nkomero",     "Gisiza",           257),
    ("Gisiza",      "Congo Nile",       416),
    ("Rubavu",      "Brasserie",        416),
    ("Gakeri",      "Nkomero",          574),
    ("Nkomero",     "Congo Nile",       653),
    ("Gakeri",      "Gisiza",           811),
    ("Congo Nile",  "Rubengera",        990),
    ("Gisiza",      "Rubengera",        1109),
    ("Gakeri",      "Congo Nile",       1227),
    ("Nkomero",     "Rubengera",        1367),
    ("Rubavu",      "Gakeri",           1604),
    ("Karongi",     "Birambo",          1663),
    ("Gisiza",      "Karongi",          1861),
    ("Gakeri",      "Rubengera",        1921),
    ("Congo Nile",  "Karongi",          1980),
    ("Nkomero",     "Karongi",          2099),
    ("Rubavu",      "Kayove",           2118),
    ("Rubavu",      "Nkomero",          2158),
    ("Congo Nile",  "Mubuga",           2158),
    ("Rubavu",      "Nkora",            2178),
    ("Congo Nile",  "Gishyita",         2396),
    ("Rubavu",      "Gisiza",           2416),
    ("Karongi",     "Gisovu",           2416),
    ("Gakeri",      "Karongi",          2674),
    ("Nkomero",     "Mubuga",           2812),
    ("Gisiza",      "Gishyita",         2812),
    ("Congo Nile",  "Mugonero",         2812),
    ("Rubavu",      "Congo Nile",       2832),
    ("Kigeyo",      "Karongi",          2970),
    ("Nkomero",     "Gishyita",         3069),
    ("Gisiza",      "Mugonero",         3228),
    ("Gakeri",      "Mubuga",           3386),
    ("Nkomero",     "Mugonero",         3485),
    ("Rubavu",      "Rubengera",        3524),
    ("Congo Nile",  "Karengera",        3524),
    ("Gakeri",      "Gishyita",         3623),
    ("Nkomero",     "Karengera",        4178),
    ("Congo Nile",  "Kirambo",          4197),
    ("Gisiza",      "Hanika",           4316),
    ("Congo Nile",  "Tyazo",            4316),
    ("Nkomero",     "Hanika",           4553),
    ("Gisiza",      "Kirambo",          4594),
    ("Congo Nile",  "Nyamasheke",       4652),
    ("Gisiza",      "Tyazo",            4732),
    ("Gakeri",      "Karengera",        4753),
    ("Nkomero",     "Kirambo",          4851),
    ("Rubavu",      "Karongi",          4950),
    ("Nkomero",     "Tyazo",            4969),
    ("Gisiza",      "Nyamasheke",       5068),
    ("Gakeri",      "Hanika",           5128),
    ("Rubavu",      "Mubuga",           5247),
    ("Nkomero",     "Nyamasheke",       5307),
    ("Gakeri",      "Kirambo",          5426),
    ("Gakeri",      "Tyazo",            5544),
    ("Rubavu",      "Gishyita",         5642),
    ("Gakeri",      "Nyamasheke",       5881),
    ("Rubavu",      "Mugonero",         5940),
    ("Congo Nile",  "Kamembe",          6138),
    ("Rubavu",      "Karengera",        6356),
    ("Gisiza",      "Kamembe",          6554),
    ("Rubavu",      "Hanika",           6731),
    ("Nkomero",     "Kamembe",          6811),
    ("Rubavu",      "Kirambo",          7029),
    ("Rubavu",      "Tyazo",            7147),
    ("Gakeri",      "Kamembe",          7365),
    ("Rubavu",      "Nyamasheke",       7721),
    ("Rubavu",      "Ntendezi",         7979),
    ("Rubavu",      "Kamembe",          9009),
]


class Command(BaseCommand):
    help = "Seed the database with RURA 2026 towns, routes, companies, buses, and trips."

    def handle(self, *args, **options):
        # ----------------------------------------------------------------
        # 1. Companies
        # ----------------------------------------------------------------
        companies = {
            name: Company.objects.get_or_create(name=name)[0]
            for name in ["Volcano Express", "Ritco Ltd", "Virunga Express"]
        }
        self.stdout.write("Companies: OK")

        # ----------------------------------------------------------------
        # 2. Towns
        # ----------------------------------------------------------------
        town_objects = {}
        for name, district in TOWNS.items():
            obj, _ = Town.objects.update_or_create(
                name=name,
                defaults={"district": district},
            )
            town_objects[name] = obj
        self.stdout.write(f"Towns: {len(town_objects)} seeded")

        # ----------------------------------------------------------------
        # 3. Buses
        # ----------------------------------------------------------------
        bus_defs = [
            ("Volcano Express", "vip",      18, "RAD100A"),
            ("Volcano Express", "standard", 30, "RAD101A"),
            ("Ritco Ltd",       "standard", 30, "RAD102A"),
            ("Virunga Express", "small",    14, "RAD103A"),
        ]
        buses = []
        for company_name, bus_type, seats, plate in bus_defs:
            bus, _ = Bus.objects.get_or_create(
                plate_number=plate,
                defaults={
                    "company":     companies[company_name],
                    "bus_type":    bus_type,
                    "total_seats": seats,
                },
            )
            buses.append(bus)
        self.stdout.write("Buses: OK")

        # ----------------------------------------------------------------
        # 4. Routes
        # ----------------------------------------------------------------
        company_list = list(companies.values())
        route_objects = []
        skipped_routes = 0
        for i, (origin_name, dest_name, price) in enumerate(ROUTES):
            origin = town_objects.get(origin_name)
            dest   = town_objects.get(dest_name)
            if not origin or not dest:
                skipped_routes += 1
                self.stdout.write(
                    self.style.WARNING(f"  Skipped: {origin_name} -> {dest_name} (town not found)")
                )
                continue
            company = company_list[i % len(company_list)]
            route, _ = Route.objects.update_or_create(
                company=company,
                origin=origin,
                destination=dest,
                defaults={"base_price": Decimal(price)},
            )
            route_objects.append(route)
        self.stdout.write(f"Routes: {len(route_objects)} seeded ({skipped_routes} skipped)")

        # ----------------------------------------------------------------
        # 5. Trips
        # ----------------------------------------------------------------
        now = timezone.now()
        trips_to_create = []
        for day_offset in range(1, 4):
            for hour in (6, 9, 14):
                for i, route in enumerate(route_objects):
                    bus = buses[i % len(buses)]
                    departure = (now + timedelta(days=day_offset)).replace(
                        hour=hour, minute=0, second=0, microsecond=0
                    )
                    trips_to_create.append(Trip(
                        route=route,
                        bus=bus,
                        departure_time=departure,
                        price=route.base_price,
                        status="scheduled",
                    ))

        Trip.objects.bulk_create(trips_to_create, ignore_conflicts=True)

        # Re-fetch with real PKs — bulk_create with ignore_conflicts=True
        # returns objects without PKs so we cannot use the return value directly.
        departure_times = list({t.departure_time for t in trips_to_create})
        created_trips = list(
            Trip.objects.filter(departure_time__in=departure_times)
            .select_related("bus")
        )
        self.stdout.write(f"Trips: {len(created_trips)} created")

        # ----------------------------------------------------------------
        # 6. Seats
        # ----------------------------------------------------------------
        seats_to_create = []
        for trip in created_trips:
            for n in range(1, trip.bus.total_seats + 1):
                seats_to_create.append(Seat(trip=trip, seat_number=n))

        Seat.objects.bulk_create(seats_to_create, ignore_conflicts=True)
        self.stdout.write(self.style.SUCCESS(
            f"Seed complete. {len(created_trips)} trips and "
            f"{len(seats_to_create)} seats created across "
            f"{len(route_objects)} routes and {len(town_objects)} towns."
        ))