# Generated by Django 6.0.6 on 2026-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_external_id', models.CharField(blank=True, default='unknown', help_text="Best-effort identifier of who triggered this call. Not all tools receive traveler_external_id as an argument, so this may be 'unknown' for tools like search_routes that don't take it.", max_length=120)),
                ('tool_name', models.CharField(max_length=80)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False, help_text="Derived from result.get('success') or result.get('found'), whichever the tool uses. True if the tool call achieved its purpose.")),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Wall-clock time the tool call took, in milliseconds.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_name', '-created_at'], name='agent_toolc_tool_na_e61879_idx'), models.Index(fields=['traveler_external_id', '-created_at'], name='agent_toolc_travele_bf797b_idx')],
            },
        ),
    ]
